### ISSUE TITLE
Hot do I use this?

### ISSUE THREAD

**Issue by asb-capfan** [wchristian/perl-tidy-komodo#1]
Hi!

Am I right that this mopdule provides a way to easily set up a Perl Tidy formatter for Komodo / Komodo IDE? 
If yes, how do I use it? Is there a manual for Setting it up? Maybe a blog post?

Thx & Kind regards

**Comment by wchristian** [comment]
Does the instruction here help? https://metacpan.org/pod/distribution/Perl-Tidy-Komodo/bin/perltidy_ko

**Comment by asb-capfan** [comment]
Hm, I would say no. I just set up perltidy without using Perl::Tidy::Komodo by looking at another source: http://www.openkomodo.com/blogs/jeffg/using-php-beautifier-komodo-ide

**Comment by wchristian** [comment]
Guess i'll have to link to that. :)

Also, cool to hear that you got perltidy set up now. As a small recommendation: I bound it to ctrl+e which makes for a very convenient shortcute. Just be aware that perltid_ko is meant to solve the issue of projects with perltidy rc files. Raw perltidy won't be able to do that.

**Comment by asb-capfan** [comment]
Actually, I prefer to have the documentation in place. The web lives and the page might disappear. That's öess likely for CPAN. I will try to create a pull request, nut it will take some time.

**Comment by wchristian** [comment]
True, i just haven't looked into how to embed pictures yet. :)

I've got it on my todo list, so it'll get done someday.

**Comment by simbabque** [comment]
Well, the link to openkomodo.com from above is dead unfortunately.

**Comment by asb-capfan** [comment]
It's this one now (but without images): http://www.activestate.com/blog/2009/03/using-php-beautifier-komodo-ide 

Basically, these are the steps:
- Get Perltidy and create a script that beautifies a piece of code. Name it perl_beautifier
- Open Komodo's preferences window and click on 'Formatters' on the left-hand side
- Click on the green 'Plus' button to add a new formatter:
- Type in the following:
- Name: Perl Beautifier ( or whatever )
- Language: Perl
- Formatter: Other Formatters => Generic Command-line Formatter
- For 'Executable to use', paste in the full path path to the 'perl_beautifier' script.
- For the command-line arguments, paste in the perl_beautifier options you would like to use.

Now, how you would want to format your code is entirely up to you. 
Have a look at the PerlTidy documentation to get a list of options.

**Comment by wchristian** [comment]
https://metacpan.org/pod/Perl::Tidy::Komodo now points at https://metacpan.org/pod/perltidy_ko and that details with pictures what to do. I'm closing this now, but let me know if i should add/change something.
